services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always
    networks:
      - glpi-net

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name: glpi
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - glpi-data:/var/www/html/glpi
      - ./wgetrc:/etc/wgetrc:ro
    environment:
      - TIMEZONE=America/Sao_Paulo
    restart: always
    networks:
      - glpi-net

networks:
  glpi-net:

volumes:
  mariadb-data:
  glpi-data:
